### ISSUE TITLE
ChatBot Page doesn't exist

### ISSUE THREAD

**Issue by faisalmujawar148** [Selasie5/AI-Customer-Support-Software#3]
The site's chatbot doesn't exist at the moment, need to get an api key as well probably <- need help with this.

**Comment by Selasie5** [comment]
Can you please elaborate on this or what specifically do you mean. Cause for now what you will have to with respect to the main software which is the chatbot will be to create the page build the UI and use the hardcoded questions and response to just make sure the basic functionality will work before we connect an APIS.

**Comment by faisalmujawar148** [comment]
I mean that if we're truly going to implement the "AI" part of the customer support software, we'll need to use some pre-exisiting LLM that we can just send requests to, so we'll need an API key for that, no?
